### ISSUE TITLE
DevelopersページのメンバーのURLを追記

### ISSUE THREAD

**Issue by ttakuma17** [team-red-22-06/git-workshop-task#65]
## 概要  
現状、Developersに記載のリンクには何も設定されておりません。
GithubもしくはTwitterのURLを記載しておきましょう。

## 目的  
Developersページが正常に機能するように修正してください。

## タスク  
細かい作業に分割してください。  
- [x] Developersページのリンクが正常に機能するか
- [x] リンク載せたくないという場合はリンクからテキストへ修正しておいてください。

**Comment by YutaUtah** [comment]
Githubでokです。
Https:/github.com/YutaUtah

**Comment by toshizo5** [comment]
OKです！
https://github.com/toshizo5

**Comment by ttakuma17** [comment]
対応済みのためcloseします
